# Generated by Django 3.1.4 on 2020-12-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='prefix',
            field=models.CharField(choices=[('Ms.', 'Ms'), ('Mrs.', 'Mrs.'), ('Miss', 'Miss'), ('Mr.', 'Mr.')], max_length=10),
        ),
    ]
